"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import {
  FileText,
  Shield,
  Users,
  Home,
  Briefcase,
  Handshake,
  Sparkles,
  Copy,
  Download,
  Check,
  ChevronDown,
} from "lucide-react"

const documentTypes = [
  {
    id: "nda",
    name: "NDA",
    fullName: "Non-Disclosure Agreement",
    icon: Shield,
  },
  {
    id: "freelance",
    name: "Freelance Contract",
    fullName: "Freelance Service Agreement",
    icon: Briefcase,
  },
  {
    id: "rental",
    name: "Rental Agreement",
    fullName: "Residential Rental Agreement",
    icon: Home,
  },
  {
    id: "employment",
    name: "Employment Letter",
    fullName: "Employment Offer Letter",
    icon: Users,
  },
  {
    id: "partnership",
    name: "Partnership Agreement",
    fullName: "Business Partnership Agreement",
    icon: Handshake,
  },
]

type GenerationState = "idle" | "generating" | "complete"

export function GenerateContent() {
  const [selectedType, setSelectedType] = useState("")
  const [isDropdownOpen, setIsDropdownOpen] = useState(false)
  const [generationState, setGenerationState] = useState<GenerationState>("idle")
  const [generatedContent, setGeneratedContent] = useState("")
  const [copied, setCopied] = useState(false)
  
  const [formData, setFormData] = useState({
    party1Name: "",
    party2Name: "",
    date: "",
    keyTerms: "",
    duration: "",
    jurisdiction: "",
  })

  const selectedDoc = documentTypes.find((d) => d.id === selectedType)

  const handleGenerate = async () => {
    setGenerationState("generating")
    setGeneratedContent("")
    
    // Simulate AI generation with progressive content
    const documentContent = generateDocumentContent()
    
    // Simulate streaming effect
    for (let i = 0; i <= documentContent.length; i += 15) {
      await new Promise((resolve) => setTimeout(resolve, 30))
      setGeneratedContent(documentContent.slice(0, i))
    }
    
    setGeneratedContent(documentContent)
    setGenerationState("complete")
  }

  const generateDocumentContent = () => {
    const doc = selectedDoc || { fullName: "Legal Document" }
    const party1 = formData.party1Name || "[Party 1]"
    const party2 = formData.party2Name || "[Party 2]"
    const date = formData.date || "[Date]"
    const jurisdiction = formData.jurisdiction || "[Jurisdiction]"
    const duration = formData.duration || "[Duration]"
    const keyTerms = formData.keyTerms || "[Key Terms]"

    return `${doc.fullName?.toUpperCase()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PARTIES TO THIS AGREEMENT

This ${doc.fullName} ("Agreement") is entered into 
as of ${date}, by and between:

PARTY 1 (First Party):
${party1}

PARTY 2 (Second Party):
${party2}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AGREEMENT DETAILS

Effective Date: ${date}
Duration: ${duration}
Governing Law: ${jurisdiction}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

KEY TERMS AND CONDITIONS

${keyTerms}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

GENERAL PROVISIONS

1. CONFIDENTIALITY
   Both parties agree to maintain the confidentiality 
   of all proprietary information disclosed during 
   the term of this Agreement.

2. TERMINATION
   Either party may terminate this Agreement with 
   30 days written notice to the other party.

3. DISPUTE RESOLUTION
   Any disputes arising from this Agreement shall 
   be resolved through binding arbitration in 
   accordance with the laws of ${jurisdiction}.

4. AMENDMENTS
   This Agreement may only be modified by written 
   consent of both parties.

5. ENTIRE AGREEMENT
   This document constitutes the entire agreement 
   between the parties and supersedes all prior 
   negotiations and agreements.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURES

Party 1: _____________________________
Name: ${party1}
Date: ${date}

Party 2: _____________________________
Name: ${party2}
Date: ${date}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Lawffle AI
This document is for reference purposes only.
Please consult a licensed attorney before signing.`
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedContent)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([generatedContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${selectedDoc?.name || "document"}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const isFormValid = selectedType && formData.party1Name && formData.party2Name

  // Reset generation when form changes
  useEffect(() => {
    if (generationState === "complete") {
      setGenerationState("idle")
    }
  }, [selectedType, formData])

  return (
    <div className="h-full">
      {/* Page Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
          Generate Document
        </h1>
        <p className="mt-1 text-muted-foreground">
          Create professional legal documents powered by AI
        </p>
      </div>

      {/* Split Screen Layout */}
      <div className="grid gap-6 lg:grid-cols-2 lg:gap-8">
        {/* LEFT SIDE - Form */}
        <div className="space-y-6">
          {/* Document Type Dropdown */}
          <div className="rounded-xl border border-border/50 bg-card p-6">
            <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              Document Type
            </h2>
            <div className="relative">
              <button
                onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                className="flex w-full items-center justify-between rounded-lg border border-border/50 bg-input px-4 py-3 text-left transition-all hover:border-border focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              >
                <span className={selectedType ? "text-foreground" : "text-muted-foreground"}>
                  {selectedDoc ? selectedDoc.name : "Select Document Type"}
                </span>
                <ChevronDown
                  className={`h-4 w-4 text-muted-foreground transition-transform ${
                    isDropdownOpen ? "rotate-180" : ""
                  }`}
                />
              </button>
              
              {isDropdownOpen && (
                <div className="absolute left-0 right-0 top-full z-10 mt-2 overflow-hidden rounded-lg border border-border/50 bg-card shadow-xl">
                  {documentTypes.map((doc) => {
                    const Icon = doc.icon
                    return (
                      <button
                        key={doc.id}
                        onClick={() => {
                          setSelectedType(doc.id)
                          setIsDropdownOpen(false)
                        }}
                        className={`flex w-full items-center gap-3 px-4 py-3 text-left transition-all hover:bg-secondary/50 ${
                          selectedType === doc.id ? "bg-primary/10 text-primary" : "text-foreground"
                        }`}
                      >
                        <Icon className="h-4 w-4" />
                        <span>{doc.name}</span>
                      </button>
                    )
                  })}
                </div>
              )}
            </div>
          </div>

          {/* Dynamic Form Fields */}
          <div
            className={`space-y-6 transition-all duration-300 ${
              selectedType ? "opacity-100" : "pointer-events-none opacity-40"
            }`}
          >
            {/* Parties Section */}
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Parties
              </h2>
              <div className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Party 1 Name</label>
                  <input
                    type="text"
                    value={formData.party1Name}
                    onChange={(e) => setFormData({ ...formData, party1Name: e.target.value })}
                    placeholder="Enter first party name"
                    className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Party 2 Name</label>
                  <input
                    type="text"
                    value={formData.party2Name}
                    onChange={(e) => setFormData({ ...formData, party2Name: e.target.value })}
                    placeholder="Enter second party name"
                    className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
              </div>
            </div>

            {/* Agreement Details Section */}
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Agreement Details
              </h2>
              <div className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <label className="text-sm font-medium text-foreground">Date</label>
                    <input
                      type="date"
                      value={formData.date}
                      onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                      className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-medium text-foreground">Duration</label>
                    <input
                      type="text"
                      value={formData.duration}
                      onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
                      placeholder="e.g., 12 months"
                      className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Key Terms</label>
                  <textarea
                    value={formData.keyTerms}
                    onChange={(e) => setFormData({ ...formData, keyTerms: e.target.value })}
                    placeholder="Describe the main terms of this agreement..."
                    rows={3}
                    className="w-full resize-none rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
              </div>
            </div>

            {/* Legal Terms Section */}
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Legal Terms
              </h2>
              <div className="space-y-2">
                <label className="text-sm font-medium text-foreground">Jurisdiction</label>
                <select
                  value={formData.jurisdiction}
                  onChange={(e) => setFormData({ ...formData, jurisdiction: e.target.value })}
                  className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  <option value="">Select jurisdiction</option>
                  <option value="India (General)">India (General)</option>
                  <option value="Uttar Pradesh, India">Uttar Pradesh</option>
                  <option value="Maharashtra, India">Maharashtra</option>
                  <option value="Delhi, India">Delhi</option>
                  <option value="Karnataka, India">Karnataka</option>
                  <option value="Tamil Nadu, India">Tamil Nadu</option>
                  <option value="Gujarat, India">Gujarat</option>
                  <option value="Rajasthan, India">Rajasthan</option>
                </select>
              </div>
            </div>

            {/* Generate Button */}
            <Button
              onClick={handleGenerate}
              disabled={!isFormValid || generationState === "generating"}
              className="h-14 w-full gap-2 bg-primary text-lg font-semibold text-primary-foreground transition-all hover:bg-primary/90 disabled:opacity-50"
            >
              {generationState === "generating" ? (
                <>
                  <div className="h-5 w-5 animate-spin rounded-full border-2 border-primary-foreground border-t-transparent" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="h-5 w-5" />
                  Generate Document
                </>
              )}
            </Button>
          </div>
        </div>

        {/* RIGHT SIDE - Document Preview */}
        <div className="flex flex-col rounded-xl border border-border/50 bg-card">
          {/* Preview Header */}
          <div className="flex items-center justify-between border-b border-border/50 px-6 py-4">
            <div className="flex items-center gap-3">
              <FileText className="h-5 w-5 text-primary" />
              <span className="font-medium text-foreground">Document Preview</span>
            </div>
            {generationState === "complete" && (
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCopy}
                  className="h-8 gap-2 text-muted-foreground hover:text-foreground"
                >
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 text-green-400" />
                      <span className="text-green-400">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4" />
                      Copy
                    </>
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownload}
                  className="h-8 gap-2 text-muted-foreground hover:text-foreground"
                >
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              </div>
            )}
          </div>

          {/* Preview Content */}
          <div className="flex-1 overflow-auto p-6">
            {generationState === "idle" && (
              <div className="flex h-full min-h-[400px] flex-col items-center justify-center text-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-secondary">
                  <FileText className="h-8 w-8 text-muted-foreground" />
                </div>
                <h3 className="text-lg font-medium text-foreground">No Document Yet</h3>
                <p className="mt-1 max-w-xs text-sm text-muted-foreground">
                  Fill in the form and click &ldquo;Generate Document&rdquo; to create your legal document
                </p>
              </div>
            )}

            {generationState === "generating" && !generatedContent && (
              <div className="min-h-[400px] space-y-4">
                {/* Loading Skeleton */}
                <div className="h-8 w-3/4 animate-pulse rounded bg-secondary" />
                <div className="h-px w-full bg-border/50" />
                <div className="space-y-2">
                  <div className="h-4 w-full animate-pulse rounded bg-secondary" />
                  <div className="h-4 w-5/6 animate-pulse rounded bg-secondary" />
                  <div className="h-4 w-4/6 animate-pulse rounded bg-secondary" />
                </div>
                <div className="h-px w-full bg-border/50" />
                <div className="space-y-2">
                  <div className="h-4 w-full animate-pulse rounded bg-secondary" />
                  <div className="h-4 w-3/4 animate-pulse rounded bg-secondary" />
                </div>
              </div>
            )}

            {generatedContent && (
              <pre className="min-h-[400px] whitespace-pre-wrap font-mono text-sm leading-relaxed text-foreground/90">
                {generatedContent}
                {generationState === "generating" && (
                  <span className="inline-block h-4 w-2 animate-pulse bg-primary" />
                )}
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
