"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import {
  FileText,
  Shield,
  Users,
  Home,
  Briefcase,
  Handshake,
  Sparkles,
  Copy,
  Download,
  Check,
  ChevronDown,
} from "lucide-react"

const documentTypes = [
  {
    id: "nda",
    name: "NDA",
    fullName: "Non-Disclosure Agreement",
    icon: Shield,
  },
  {
    id: "freelance",
    name: "Freelance Contract",
    fullName: "Freelance Service Agreement",
    icon: Briefcase,
  },
  {
    id: "rental",
    name: "Rental Agreement",
    fullName: "Residential Rental Agreement",
    icon: Home,
  },
  {
    id: "employment",
    name: "Employment Letter",
    fullName: "Employment Offer Letter",
    icon: Users,
  },
  {
    id: "partnership",
    name: "Partnership Agreement",
    fullName: "Business Partnership Agreement",
    icon: Handshake,
  },
]

type GenerationState = "idle" | "generating" | "complete"
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000"

export function GenerateContent() {
  const [selectedType, setSelectedType] = useState("")
  const [isDropdownOpen, setIsDropdownOpen] = useState(false)
  const [generationState, setGenerationState] = useState<GenerationState>("idle")
  const [fullGeneratedContent, setFullGeneratedContent] = useState("")
  const [generatedContent, setGeneratedContent] = useState("")
  const [copied, setCopied] = useState(false)
  const [error, setError] = useState("")
  
  const [formData, setFormData] = useState({
    party1Name: "",
    party2Name: "",
    date: "",
    keyTerms: "",
    duration: "",
    jurisdiction: "",
  })

  const selectedDoc = documentTypes.find((d) => d.id === selectedType)

  const handleGenerate = async () => {
    if (!selectedDoc) return

    setGenerationState("generating")
    setError("")
    setFullGeneratedContent("")
    setGeneratedContent("")

    try {
      const response = await fetch(`${API_BASE_URL}/api/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          docType: selectedDoc.name,
          fields: formData,
        }),
      })

      const payload = await response.json()

      if (!response.ok) {
        throw new Error(payload.error || "Failed to generate document.")
      }

      const document = typeof payload.document === "string" ? payload.document : ""
      if (!document.trim()) {
        throw new Error("No document content received from server.")
      }

      setFullGeneratedContent(document)
      setGenerationState("complete")
    } catch (err) {
      const message = err instanceof Error ? err.message : "Something went wrong. Please try again."
      setError(message)
      setGenerationState("idle")
    }
  }

  const handleCopy = async () => {
    if (!fullGeneratedContent) return
    try {
      await navigator.clipboard.writeText(fullGeneratedContent)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (_err) {
      setError("Unable to copy text. Please try again.")
    }
  }

  const handleDownload = async () => {
    if (!fullGeneratedContent) return

    try {
      if (typeof window === "undefined") return

      const { jsPDF } = await import("jspdf")
      const pdf = new jsPDF({ unit: "pt", format: "a4" })
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - margin * 2
      const bottomLimit = pageHeight - margin

      const title = (selectedDoc?.fullName || selectedDoc?.name || "Legal Document").toUpperCase()
      let y = margin + 10

      const ensurePageSpace = (requiredHeight: number) => {
        if (y + requiredHeight > bottomLimit) {
          pdf.addPage()
          y = margin + 10
        }
      }

      // Title block
      pdf.setFont("times", "bold")
      pdf.setFontSize(17)
      const titleWidth = pdf.getTextWidth(title)
      const titleX = (pageWidth - titleWidth) / 2
      pdf.text(title, titleX, y)
      y += 18

      pdf.setLineWidth(0.8)
      pdf.line(margin, y, pageWidth - margin, y)
      y += 20

      const normalizedLines = fullGeneratedContent
        .split("\n")
        .map((line) => line.trim())
        .filter((line) => line.length > 0)

      normalizedLines.forEach((line) => {
        const isSectionHeading =
          line.length <= 70 &&
          line === line.toUpperCase() &&
          /[A-Z]/.test(line) &&
          !line.includes(":") &&
          !line.startsWith("Generated by")

        if (isSectionHeading) {
          ensurePageSpace(26)
          pdf.setFont("times", "bold")
          pdf.setFontSize(12.5)
          pdf.text(line, margin, y)
          y += 16
          return
        }

        pdf.setFont("times", "normal")
        pdf.setFontSize(11)
        const wrapped = pdf.splitTextToSize(line, contentWidth) as string[]
        const paragraphHeight = wrapped.length * 14
        ensurePageSpace(paragraphHeight + 10)
        pdf.text(wrapped, margin, y)
        y += paragraphHeight + 8
      })

      pdf.save("document.pdf")
    } catch (_err) {
      setError("Unable to download PDF. Please try again.")
    }
  }

  const isFormValid = selectedType && formData.party1Name && formData.party2Name

  // Reset generation when form changes
  useEffect(() => {
    if (generationState === "complete") {
      setGenerationState("idle")
    }
    setFullGeneratedContent("")
    setGeneratedContent("")
    setError("")
  }, [selectedType, formData])

  useEffect(() => {
    if (!fullGeneratedContent) {
      setGeneratedContent("")
      return
    }

    setGeneratedContent("")
    let index = 0

    const interval = setInterval(() => {
      index += 1
      setGeneratedContent(fullGeneratedContent.slice(0, index))
      if (index >= fullGeneratedContent.length) {
        clearInterval(interval)
      }
    }, 10)

    return () => clearInterval(interval)
  }, [fullGeneratedContent])

  return (
    <div className="h-full">
      {/* Page Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
          Generate Document
        </h1>
        <p className="mt-1 text-muted-foreground">
          Create professional legal documents powered by AI
        </p>
      </div>

      {/* Split Screen Layout */}
      <div className="grid gap-6 lg:grid-cols-2 lg:gap-8">
        {/* LEFT SIDE - Form */}
        <div className="space-y-6">
          {/* Document Type Dropdown */}
          <div className="rounded-xl border border-border/50 bg-card p-6">
            <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              Document Type
            </h2>
            <div className="relative">
              <button
                onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                className="flex w-full items-center justify-between rounded-lg border border-border/50 bg-input px-4 py-3 text-left transition-all hover:border-border focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              >
                <span className={selectedType ? "text-foreground" : "text-muted-foreground"}>
                  {selectedDoc ? selectedDoc.name : "Select Document Type"}
                </span>
                <ChevronDown
                  className={`h-4 w-4 text-muted-foreground transition-transform ${
                    isDropdownOpen ? "rotate-180" : ""
                  }`}
                />
              </button>
              
              {isDropdownOpen && (
                <div className="absolute left-0 right-0 top-full z-10 mt-2 overflow-hidden rounded-lg border border-border/50 bg-card shadow-xl">
                  {documentTypes.map((doc) => {
                    const Icon = doc.icon
                    return (
                      <button
                        key={doc.id}
                        onClick={() => {
                          setSelectedType(doc.id)
                          setIsDropdownOpen(false)
                        }}
                        className={`flex w-full items-center gap-3 px-4 py-3 text-left transition-all hover:bg-secondary/50 ${
                          selectedType === doc.id ? "bg-primary/10 text-primary" : "text-foreground"
                        }`}
                      >
                        <Icon className="h-4 w-4" />
                        <span>{doc.name}</span>
                      </button>
                    )
                  })}
                </div>
              )}
            </div>
          </div>

          {/* Dynamic Form Fields */}
          <div
            className={`space-y-6 transition-all duration-300 ${
              selectedType ? "opacity-100" : "pointer-events-none opacity-40"
            }`}
          >
            {/* Parties Section */}
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Parties
              </h2>
              <div className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Party 1 Name</label>
                  <input
                    type="text"
                    value={formData.party1Name}
                    onChange={(e) => setFormData({ ...formData, party1Name: e.target.value })}
                    placeholder="Enter first party name"
                    className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Party 2 Name</label>
                  <input
                    type="text"
                    value={formData.party2Name}
                    onChange={(e) => setFormData({ ...formData, party2Name: e.target.value })}
                    placeholder="Enter second party name"
                    className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
              </div>
            </div>

            {/* Agreement Details Section */}
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Agreement Details
              </h2>
              <div className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <label className="text-sm font-medium text-foreground">Date</label>
                    <input
                      type="date"
                      value={formData.date}
                      onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                      className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-medium text-foreground">Duration</label>
                    <input
                      type="text"
                      value={formData.duration}
                      onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
                      placeholder="e.g., 12 months"
                      className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Key Terms</label>
                  <textarea
                    value={formData.keyTerms}
                    onChange={(e) => setFormData({ ...formData, keyTerms: e.target.value })}
                    placeholder="Describe the main terms of this agreement..."
                    rows={3}
                    className="w-full resize-none rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground placeholder:text-muted-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  />
                </div>
              </div>
            </div>

            {/* Legal Terms Section */}
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Legal Terms
              </h2>
              <div className="space-y-2">
                <label className="text-sm font-medium text-foreground">Jurisdiction</label>
                <select
                  value={formData.jurisdiction}
                  onChange={(e) => setFormData({ ...formData, jurisdiction: e.target.value })}
                  className="w-full rounded-lg border border-border/50 bg-input px-4 py-3 text-foreground transition-all focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  <option value="">Select jurisdiction</option>
                  <option value="India (General)">India (General)</option>
                  <option value="Uttar Pradesh, India">Uttar Pradesh</option>
                  <option value="Maharashtra, India">Maharashtra</option>
                  <option value="Delhi, India">Delhi</option>
                  <option value="Karnataka, India">Karnataka</option>
                  <option value="Tamil Nadu, India">Tamil Nadu</option>
                  <option value="Gujarat, India">Gujarat</option>
                  <option value="Rajasthan, India">Rajasthan</option>
                </select>
              </div>
            </div>

            {/* Generate Button */}
            <Button
              onClick={handleGenerate}
              disabled={!isFormValid || generationState === "generating"}
              className="h-14 w-full gap-2 bg-primary text-lg font-semibold text-primary-foreground transition-all hover:bg-primary/90 disabled:opacity-50"
            >
              {generationState === "generating" ? (
                <>
                  <div className="h-5 w-5 animate-spin rounded-full border-2 border-primary-foreground border-t-transparent" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="h-5 w-5" />
                  Generate Document
                </>
              )}
            </Button>
            {error && <p className="text-sm text-red-400">{error}</p>}
          </div>
        </div>

        {/* RIGHT SIDE - Document Preview */}
        <div className="flex flex-col rounded-xl border border-border/50 bg-card">
          {/* Preview Header */}
          <div className="flex items-center justify-between border-b border-border/50 px-6 py-4">
            <div className="flex items-center gap-3">
              <FileText className="h-5 w-5 text-primary" />
              <span className="font-medium text-foreground">Document Preview</span>
            </div>
            {generationState === "complete" && (
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCopy}
                  className="h-8 gap-2 text-muted-foreground hover:text-foreground"
                >
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 text-green-400" />
                      <span className="text-green-400">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4" />
                      Copy
                    </>
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownload}
                  className="h-8 gap-2 text-muted-foreground hover:text-foreground"
                >
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              </div>
            )}
          </div>

          {/* Preview Content */}
          <div className="flex-1 overflow-auto p-6">
            {generationState === "idle" && (
              <div className="flex h-full min-h-[400px] flex-col items-center justify-center text-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-secondary">
                  <FileText className="h-8 w-8 text-muted-foreground" />
                </div>
                <h3 className="text-lg font-medium text-foreground">No Document Yet</h3>
                <p className="mt-1 max-w-xs text-sm text-muted-foreground">
                  Fill in the form and click &ldquo;Generate Document&rdquo; to create your legal document
                </p>
              </div>
            )}

            {generationState === "generating" && !generatedContent && (
              <div className="min-h-[400px] space-y-4">
                {/* Loading Skeleton */}
                <div className="h-8 w-3/4 animate-pulse rounded bg-secondary" />
                <div className="h-px w-full bg-border/50" />
                <div className="space-y-2">
                  <div className="h-4 w-full animate-pulse rounded bg-secondary" />
                  <div className="h-4 w-5/6 animate-pulse rounded bg-secondary" />
                  <div className="h-4 w-4/6 animate-pulse rounded bg-secondary" />
                </div>
                <div className="h-px w-full bg-border/50" />
                <div className="space-y-2">
                  <div className="h-4 w-full animate-pulse rounded bg-secondary" />
                  <div className="h-4 w-3/4 animate-pulse rounded bg-secondary" />
                </div>
              </div>
            )}

            {generatedContent && (
              <pre className="min-h-[400px] whitespace-pre-wrap font-mono text-sm leading-relaxed text-foreground/90">
                {generatedContent}
                {(generationState === "generating" || generatedContent.length < fullGeneratedContent.length) && (
                  <span className="inline-block h-4 w-2 animate-pulse bg-primary" />
                )}
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
